exclude:
  - node_modules
  - package*.json
  - yarn.lock
  - Gemfile*
  - README*
  - .gitignore
  - .github
  # - scripts   <-- REMOVE or comment out this line
  - assets/raw/
  - media/originals/
  - **/*.psd
  - **/*.ai
  - **/*.zip
  - **/*.map
  - **/*.mov
  - **/*.mp4