# _config.yml
exclude:
  - node_modules
  - package*.json
  - yarn.lock
  - Gemfile*
  - README*
  - .gitignore
  - .github
  - scripts
  - assets/raw/           # originals, PSDs, videos, etc.
  - media/originals/
  - **/*.psd
  - **/*.ai
  - **/*.zip
  - **/*.map              # JS/CSS source maps
  - **/*.mov
  - **/*.mp4
